//
// Created by foyjog on 14/12/2021.
//

#include <yaml.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "yaml_parse.h"


/*
 * Consume yaml events generated by the libyaml parser to
 * import our data into raw c data structures. Error processing
 * is keep to a mimimum since this is just an example.
 */
int consume_event(struct parser_state *s, yaml_event_t *event)
{
    char *value;

    switch (s->state) {
        case STATE_START:
            switch (event->type) {
                case YAML_STREAM_START_EVENT:
                    s->state = STATE_STREAM;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_STREAM:
            switch (event->type) {
                case YAML_DOCUMENT_START_EVENT:
                    s->state = STATE_DOCUMENT;
                    break;
                case YAML_STREAM_END_EVENT:
                    s->state = STATE_STOP;  /* All done. */
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_DOCUMENT:
            switch (event->type) {
                case YAML_MAPPING_START_EVENT:
                    s->state = STATE_SECTION;
                    break;
                case YAML_DOCUMENT_END_EVENT:
                    s->state = STATE_STREAM;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_SECTION:
            switch (event->type) {
                case YAML_SCALAR_EVENT:
                    value = (char *)event->data.scalar.value;
                    if (strcmp(value, "rules") == 0) {
                        s->state = STATE_RLIST;
                    } else {
                        fprintf(stderr, "Unexpected scalar: %s\n", value);
                        return FAILURE;
                    }
                    break;
                case YAML_DOCUMENT_END_EVENT:
                    s->state = STATE_STREAM;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_RLIST:
            switch (event->type) {
                case YAML_SEQUENCE_START_EVENT:
                    s->state = STATE_RVALUES;
                    break;
                case YAML_MAPPING_END_EVENT:
                    s->state = STATE_SECTION;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_RVALUES:
            switch (event->type) {
                case YAML_MAPPING_START_EVENT:
                    s->state = STATE_RKEY;
                    break;
                case YAML_SEQUENCE_END_EVENT:
                    s->state = STATE_RLIST;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_RKEY:
            switch (event->type) {
                case YAML_SCALAR_EVENT:
                    value = (char *)event->data.scalar.value;
                    if (strcmp(value, "name") == 0) {
                        s->state = STATE_RNAME;
                    } else if (strcmp(value, "description") == 0) {
                        s->state = STATE_RDESCIPTION;
                    } else if (strcmp(value, "condition") == 0) {
                        s->state = STATE_RCONDITION;
                    } else if (strcmp(value, "priority") == 0) {
                        s->state = STATE_RPRIORITY;
                    } else {
                        fprintf(stderr, "Unexpected key: %s\n", value);
                        return FAILURE;
                    }
                    break;
                case YAML_MAPPING_END_EVENT:
                    add_rule(&s->flist, s->f.rule_name, s->f.description, s->f.condition, s->f.priority);
                    free(s->f.rule_name);
                    free(s->f.description);
                    free(s->f.condition);
                    memset(&s->f, 0, sizeof(s->f));
                    s->state = STATE_RVALUES;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_RNAME:
            switch (event->type) {
                case YAML_SCALAR_EVENT:
                    if (s->f.rule_name) {
                        fprintf(stderr, "Warning: duplicate 'rule_name' key.\n");
                        free(s->f.rule_name);
                    }
                    s->f.rule_name = bail_strdup((char *)event->data.scalar.value);
                    s->state = STATE_RKEY;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_RDESCIPTION:
            switch (event->type) {
                case YAML_SCALAR_EVENT:
                    if (s->f.description) {
                        fprintf(stderr, "Warning: duplicate 'description' key.\n");
                        free(s->f.description);
                    }
                    s->f.description = bail_strdup((char *)event->data.scalar.value);
                    s->state = STATE_RKEY;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_RCONDITION:
            switch (event->type) {
                case YAML_SCALAR_EVENT:
                    if (s->f.condition) {
                        fprintf(stderr, "Warning: duplicate 'condition' key.\n");
                        free(s->f.condition);
                    }
                    s->f.condition = bail_strdup((char *)event->data.scalar.value);
                    s->state = STATE_RKEY;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;
        case STATE_RPRIORITY:
            switch (event->type) {
                case YAML_SCALAR_EVENT:
                    if (s->f.priority) {
                        fprintf(stderr, "Warning: duplicate 'condition' key.\n");
                    }
                    s->f.priority =  atoi((char *)event->data.scalar.value);
                    s->state = STATE_RKEY;
                    break;
                default:
                    fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
                    return FAILURE;
            }
            break;

        case STATE_STOP:
            break;
    }
    return SUCCESS;
}